[package]
name = "cxx2flow"
version = "0.1.1"
edition = "2018"
description = "Convert your C/C++ code to control flow graph"
license = "MIT"
repository = "https://github.com/Enter-tainer/cxx2flow"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.42"
clap = "2.33.3"
log = "0.4.14"
tree-sitter = "0.19.5"
tree-sitter-cpp = "0.19.0"

[profile.release]
lto = "fat"